branch_whitelist = [ "main", "release/**" ]
pre_bump_hooks = [
    "cargo build --release",
    "echo 'bumping from {{latest}} to {{version}}'",
    "cargo bump {{version}}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "ontime"
owner = "mbhall88"
authors = [
    { signature = "Michael Hall", username = "mbhall88" },
]